/**
 * Augments the Env interface generated by `wrangler types` with secrets
 * that are not declared in wrangler.toml — these are injected at deploy
 * time by the Doppler → wrangler secret bulk sync in CI.
 */
interface Env {
  ENVIRONMENT: string;
}
